/**
 * Generates the roster and prepares the Votes tab.
 *
 * Run after the Attendees masterlist changes:  pnpm seed
 *
 * This is the single origin for both copies of the member list — the picker's
 * `lib/roster.ts` constant and the seeded rows in the Votes tab — so the two cannot
 * drift apart. Re-running is safe: ballots already cast are read back and preserved.
 */
import { writeFileSync } from 'node:fs'
import {
  VOTES_TAB,
  VOTE_HEADERS,
  createTab,
  readMasterlist,
  readVoteSerials,
  readVotes,
  tabTitles,
  writeRange,
  type CellValue,
} from '../lib/sheets'

const ROSTER_PATH = new URL('../lib/roster.ts', import.meta.url).pathname

async function main() {
  const names = await readMasterlist()
  if (names.length === 0) throw new Error('Attendees tab returned no names — refusing to seed.')
  console.log(`Read ${names.length} names from the masterlist.`)

  if (!(await tabTitles()).includes(VOTES_TAB)) {
    await createTab(VOTES_TAB)
    console.log(`Created the ${VOTES_TAB} tab.`)
  }

  // Preserve anything already cast. Keyed by name, because a member's row index
  // shifts whenever the masterlist gains or loses someone.
  const existing = new Map((await readVotes()).map((v) => [v.name, v]))

  // Column A is a date, and `readVotes` hands back the text it displays as. Writing
  // that back would leave a string behind the "Month Day Year" format, so the serial
  // is read separately and carried across untouched.
  const serials = await readVoteSerials()
  const kept = names.filter((n) => existing.get(n)?.votedAt).length

  const rows: CellValue[][] = names.map((name) => {
    const prior = existing.get(name)
    return [
      serials.get(name) ?? '',
      name,
      prior?.track ?? '',
      prior?.date ?? '',
      prior?.venue ?? '',
      prior?.food ?? '',
      prior?.palette ?? '',
      prior?.attending ?? '',
    ]
  })

  // Pad past the previous extent so removed members leave no orphan rows behind.
  const padTo = Math.max(rows.length, existing.size) + 1
  while (rows.length < padTo) rows.push(Array<CellValue>(VOTE_HEADERS.length).fill(''))

  await writeRange(`${VOTES_TAB}!A1:H${rows.length + 1}`, [[...VOTE_HEADERS], ...rows])
  console.log(`Seeded ${names.length} rows into ${VOTES_TAB} (${kept} existing ballots preserved).`)

  writeFileSync(
    ROSTER_PATH,
    `// Generated by scripts/seed-roster.ts — do not edit by hand.\n` +
      `// Source: the Attendees tab of the reunion workbook. Regenerate with \`pnpm seed\`.\n\n` +
      `export const ROSTER = [\n${names.map((n) => `  ${JSON.stringify(n)},`).join('\n')}\n] as const\n\n` +
      `export type MemberName = (typeof ROSTER)[number]\n\n` +
      `export const isMember = (name: string): boolean =>\n` +
      `  (ROSTER as readonly string[]).includes(name)\n`,
  )
  console.log(`Wrote lib/roster.ts.`)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
